// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using it3045_finalproject.Data;

#nullable disable

namespace it3045_finalproject.Migrations
{
    [DbContext(typeof(DefaultContext))]
    [Migration("20260421210841_NewEntities")]
    partial class NewEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("it3045_finalproject.Models.ChipotleMenu", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ItemCost")
                        .HasColumnType("float");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemId");

                    b.ToTable("ChipotleMenus");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            Description = "A burrito is a type of Mexican food that consists of a flour tortilla wrapped around a filling, which can include various ingredients such as rice, beans, meat, cheese, and vegetables.",
                            ItemCost = 10.0,
                            ItemName = "Burrito",
                            ItemType = "Entree"
                        },
                        new
                        {
                            ItemId = 2,
                            Description = "A bowl is a dish that consists of a base of rice or lettuce topped with various ingredients such as beans, meat, cheese, and vegetables. It is similar to a burrito but without the tortilla.",
                            ItemCost = 9.5,
                            ItemName = "Bowl",
                            ItemType = "Entree"
                        },
                        new
                        {
                            ItemId = 3,
                            Description = "Soft or crispy tortillas filled with meat, salsa, and toppings.",
                            ItemCost = 8.25,
                            ItemName = "Tacos",
                            ItemType = "Entree"
                        },
                        new
                        {
                            ItemId = 4,
                            Description = "Grilled tortilla stuffed with cheese and optional fillings.",
                            ItemCost = 7.75,
                            ItemName = "Quesadilla",
                            ItemType = "Entree"
                        },
                        new
                        {
                            ItemId = 5,
                            Description = "Crispy chips served with fresh guacamole.",
                            ItemCost = 3.5,
                            ItemName = "Chips & Guacamole",
                            ItemType = "Side"
                        });
                });

            modelBuilder.Entity("it3045_finalproject.Models.Hobbies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HobbiesId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hobbies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Usually play in my free time",
                            HobbiesId = 1,
                            Name = "Video Games"
                        },
                        new
                        {
                            Id = 2,
                            Description = "I like to cook in my free time",
                            HobbiesId = 2,
                            Name = "Cooking"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Exploring trails and nature on weekends",
                            HobbiesId = 3,
                            Name = "Hiking"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Taking photos of landscapes and people",
                            HobbiesId = 4,
                            Name = "Photography"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Enjoy reading fiction and non-fiction books",
                            HobbiesId = 5,
                            Name = "Reading"
                        });
                });

            modelBuilder.Entity("it3045_finalproject.Models.MicrosoftServices", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<string>("ServiceCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SubscriptionCost")
                        .HasColumnType("float");

                    b.HasKey("ServiceId");

                    b.ToTable("MicrosoftServices");

                    b.HasData(
                        new
                        {
                            ServiceId = 1,
                            ServiceCategory = "Cloud Computing",
                            ServiceDescription = "Azure is a cloud computing platform and service created by Microsoft. It provides a wide range of cloud services, including those for computing, analytics, storage, and networking.",
                            ServiceName = "Azure",
                            SubscriptionCost = 23.989999999999998
                        },
                        new
                        {
                            ServiceId = 2,
                            ServiceCategory = "Productivity",
                            ServiceDescription = "Office 365 is a subscription-based service that provides access to productivity applications such as Word, Excel, PowerPoint, Outlook, and OneDrive.",
                            ServiceName = "Office 365",
                            SubscriptionCost = 12.99
                        },
                        new
                        {
                            ServiceId = 3,
                            ServiceCategory = "Collaboration",
                            ServiceDescription = "A collaboration platform that combines chat, meetings, notes, and attachments.",
                            ServiceName = "Microsoft Teams",
                            SubscriptionCost = 5.0
                        },
                        new
                        {
                            ServiceId = 4,
                            ServiceCategory = "Storage",
                            ServiceDescription = "Cloud storage service that allows users to store files and access them from any device.",
                            ServiceName = "OneDrive",
                            SubscriptionCost = 1.99
                        },
                        new
                        {
                            ServiceId = 5,
                            ServiceCategory = "Analytics",
                            ServiceDescription = "Business analytics service that provides interactive visualizations and business intelligence capabilities.",
                            ServiceName = "Power BI",
                            SubscriptionCost = 9.9900000000000002
                        });
                });

            modelBuilder.Entity("it3045_finalproject.Models.TeamMember", b =>
                {
                    b.Property<int>("TeamMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamMemberId"));

                    b.Property<string>("TeamMemberBirthdate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamMemberName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamMemberProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamMemberYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamMemberId");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            TeamMemberId = 1,
                            TeamMemberBirthdate = "01/01/2005",
                            TeamMemberName = "Aneesh Palande",
                            TeamMemberProgram = "Game Development and Simulation",
                            TeamMemberYear = "Pre-Junior"
                        },
                        new
                        {
                            TeamMemberId = 2,
                            TeamMemberBirthdate = "01/01/2005",
                            TeamMemberName = "Alex Lauffenburger",
                            TeamMemberProgram = "Cyber Security",
                            TeamMemberYear = "Pre-Junior"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
